= Feature highlights
:imagesdir: ../assets/images

Philosophy::
* Our mindset is based on decade long world-leading drone swarm research plus drone show services since 2015
* We only sell software that we test and use actively ourselves
* Skybrush Suite and our professional team guides you through the whole process of drone shows from design to execution and beyond

Platform::
* Platform-independent modular design - Linux, macOS and Windows 10 versions available
* Server-client architecture for flexible support of customer needs

Drone compatibility::
* Latest stable ArduCopter codebase with dedicated show flight mode
* Compatible with most of the show drones built on autopilots of the Pixhawk family
* DJI Matrice series support for non-show applications on request
* CollMot's FlockCtrl support for onboard swarm level intelligence (e.g. automatic swarm-level path planning and collision avoidance)
* Modular and clean structure enables simple integration of new drone types upon request

Layout::
* Clean GUI with mouse and touch screen support
* Handy keyboard shortcuts enable quick individual or fleet control

Dedicated features::
* RTK correction transmission through the secondary radio link
* Plug-and-play compatiblility with *Skybrush Server* for enhanced status feedback

Safety::
* Independent secondary communication channel running on independent GCS hardware
* Individual and fleet-level control features
* Operator can interrupt show any time with fleet-level Land / Return-to-home / Halt (kill switch) buttons
