= Hardware requirements
:imagesdir: ../assets/images

A full hardware setup needed for *Skybrush Sidekick* to control drone fleets consists of the following components:

*Mandatory requirements*

  * A laptop or desktop machine running *Skybrush Sidekick*
  * Compatible drone fleet
  * 433/868/900 MHz radio (depending on local regulatory requirements) connected to both the GCS laptop and the drones

*Optional requirements*

  * A laptop or desktop machine or dedicated hardware that runs *Skybrush Server*. This can be the same device running *Skybrush Sidekick* or an independent one, although a separate machine is recommended to provide a truly independent connection that remains operational even if your main laptop malfunctions.
  * Wifi network to which both *Skybrush Server* and *Skybrush Sidekick* can be connected in order to receive drone status feed in *Skybrush Sidekick* from the active *Skybrush Server*.
  * RTK base station or NTRIP-based RTK correction source connected to *Skybrush Server*. If present, corrections can be sent to the drones through the secondary communication channel from *Skybrush Sidekick*.

== Recommended GCS configuration

The recommended configuration for the ground control device (laptop) running *Skybrush Sidekick* is the following:

  * at least an Intel Core i5 or equivalent CPU
  * At least 2 GB of RAM (4 GB preferred)
  * Supported OS: Windows 10, Linux or macOS 10.14 or later

== Communication with drones

* *Skybrush Sidekick* communicates with the drones on a 433/866/900 MHz radio channel with unidirectional messages being sent from *Skybrush Sidekick* towards the drones. Note that telemetry or any kind of response from the drones towards *Skybrush Sidekick* is _NOT_ available on this channel.

* *Skybrush Sidekick* may receive status messages from the drones through *Skybrush Server* and the primary wifi network behind. This allows for visual status indication in *Skybrush Sidekick* as an optional enhancement, but the core functionality of *Skybrush Sidekick* _DOES NOT_ depend on the state of the *Skybrush Server*.

== Supported drones

*Skybrush Sidekick* supports the same drones as *Skybrush Live*. Please see the full list there.

== Supported radio hardware

The default radio that can be used as a secondary communication channel is the https://ardupilot.org/copter/docs/common-sik-telemetry-radio.html[3DR SiK Telemetry Radio].

However, several fully functional clones are also available, including, e.g., these:

* https://store.mrobotics.io/product-p/mro-sikv2airgnd-mr.htm[mRobotics SiK Telemetry Radio V2 Air/Ground Bundle]
* https://shop.holybro.com/transceiver-telemetry-radio-v3_p1103.html[Holybro Transceiver Telemetry Radio V3]
* https://store.rfdesign.com.au/rfd-868-modem/[RFDesign RFD 868+ Modem]
* https://store.rfdesign.com.au/rfd-900p-modem/[RFDesign RFD 900+ Modem]

The custom firmware we provide for these radios may be compatible with other radios based on the SiLabs Si10xx chipsets. mailto:support@collmot.com[Contact us] for details in case you wish to use a radio not listed here.

== Supported RTK base stations

*Skybrush Sidekick* supports RTK base stations through *Skybrush Server*. Please check out the related documentation of *Skybrush Live* for more details.
