= Hotkeys
:imagesdir: ../assets/images
:experimental:

The keyboard input of *Skybrush Sidekick* is optimised to reduce reaction time of fleet control as much as possible through the following handy features:

* To select a single drone, just type in its numeric ID and press kbd:[Enter]. Alternatively, you can also use the arrow keys or the cursor (with a mouse, touchpad or touchscreen) to navigate to the desired drone ID.

* To switch to broadcasting mode without explicit selection, just press kbd:[Esc]

* To send commands to the selected drones (or all drones in the absence of a selection), press the hotkeys listed at the bottom of the control panel.

* The hotkeys for selecting a single drone _and_ subsequently sending a command can be merged and the kbd:[Enter] key at the end of the drone selection keyboard sequence can be omitted in this case; for instance, typing kbd:[1] kbd:[4] kbd:[7] kbd:[L] will land drone 147 immediately.

.Control command hotkeys
[%autowidth]
|===
|Keyboard shortcut|Function

|kbd:[W]|Flash LED of selected/all drones
|kbd:[S]|Activate _show_ flight mode on selected/all drones
|kbd:[P]|Activate _position hold_ flight mode on selected/all drones
|kbd:[R]|Activate _return to home_ flight mode on selected/all drones
|kbd:[L]|Activate _land_ flight mode on selected/all drones
|kbd:[Shift+X]|Disarm motors of selected/all drones
|===

WARNING: The hotkey descriptions on the control panel explicitely define whether the hotkeys refer to the selection or all drones. A confirmation dialog prevents the accidental activation of a command in broadcast mode by default, but these confirmations can be turned off. Always double check that you send commands to only those drones that you really want to control. 
