= Software installation
:imagesdir: ../assets/images
:experimental:

*Skybrush Sidekick* comes in an installation package. Installation is very straightforward and takes only a short time. Please follow the guide below according to your preferred operating system.


== Installation on Windows

On Windows 10, *Skybrush Sidekick* comes in an installation package. Click on the received single executable (.exe) and follow the steps of the installation.

Select whether you would like to install *Skybrush Sidekicj* for the current user or for all users on your system, select the destination of the installation and press the btn:[Install] button.

The installation creates a shortcut icon on your Desktop and adds *Skybrush Sidekick* to the list of applications in your Start Menu.


== Installation on Linux

On Linux platforms, *Skybrush Sidekick* comes as a single AppImage executable that can be executed from the command line or by double-clicking on it in the file manager of your choice. No installation is needed.


== Installation on macOS

On macOS platforms (10.15 or later) *Skybrush Sidekick* comes as a single disc image file (.dmg) that you need to open in Finder by double-clicking on it. Then you need to drag the new *Skybrush Sidekick* icon over the Applications folder to install it. *Skybrush Sidekick* can then be invoked from the Applications folder.

NOTE: *Skybrush Sidekick* has no digital signature at the moment. As a consequence, the Gatekeeper security mechanism built into recent macOS versions may prevent the application from starting up. If this happens, _right-click_ on the icon of *Skybrush Live* (or hold down the kbd:[⌘] key while clicking), and then select menu:Open from the pop-up menu, then confirm your choice by clicking on the btn:[Open] button again in the pop-up dialog. This will allow *Skybrush Live* to bypass Gatekeeper security checks in the future.


== Uninstalling components

=== Uninstallation on Windows

If you need to uninstall Skybrush components from your system for any reason, https://support.microsoft.com/en-us/windows/uninstall-or-remove-apps-and-programs-in-windows-10-4b55f974-2cc6-2d2b-d092-5905080eaf98[follow the official instructions from the Windows 10 support page] to remove them.

=== Uninstallation on Linux

Simply remove the AppImage file from your system ot uninstall *Skybrush Sidekick*.

=== Uninstallation on macOS

Simply drag the *Skybrush Sidekick* icon from your Applications folder to the Bin on the Dock at the bottom of the screen to uninstall *Skybrush Sidekick*.

