nodeLinker: node-modules

npmScopes:
  skybrush:
    npmRegistryServer: "https://npm.collmot.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
